box:
  knife:
    price: 200
    unit: all
  bigSize:
    width: 899
    length: 1194
    unit: mm
  smallSize:
    width: 787
    length: 1080
    unit: mm
  priceList:
    price:
      big:
        grey:
          250g: 1.35
          300g: 1.6
          350g: 1.85
          400g: 2.2
        white:
          250g: 1.95
          300g: 2.35
          350g: 2.75
          400g: 3.1
      small:
        grey:
          250g: 1.07
          300g: 1.3
          350g: 1.5
          400g: 1.7
        white:
          250g: 1.55
          300g: 1.86
          350g: 2.2
          400g: 2.5
    unit: piece
  process:
    emboss:
      price: 0.06
      unit: one
    print:
      price: 0.5
      unit: piece
    corrugate:
      price: 1.8
      unit: m^2
    laminate:
      price: 0.6
      unit: m^2
    gold:
      big:
        price: 1.8
        unit: m^2
      small:
        price: 1.5
        unit: m^2
      extra:
        price: 0.15
        unit: piece
    uv:
      big:
        price: 1.5
        unit: m^2
      small:
        price: 0.2
        unit: piece
      threshold: 300
  scale: 1.0
book: todo
label:
  price:
    general: 3.5
    removable: 3.8
    pvc: 6
  unit: m^2
  scale: 1.0
