box:
  knife:
    price: 200
    unit: all
  bigSize:
    width: 889
    length: 1194
    unit: mm
  smallSize:
    width: 787
    length: 1080
    unit: mm
  priceList:
    price:
      big:
        grey:
          250g: 1.35
          300g: 1.6
          350g: 1.85
          400g: 2.2
        white:
          250g: 1.95
          300g: 2.35
          350g: 2.75
          400g: 3.1
      small:
        grey:
          250g: 1.07
          300g: 1.3
          350g: 1.5
          400g: 1.7
        white:
          250g: 1.55
          300g: 1.86
          350g: 2.2
          400g: 2.5
    unit: piece
  process:
    emboss:
      price: 0.06
      unit: one
    print:
      price: 0.5
      unit: piece
    corrugate:
      price: 1.8
      unit: m^2
    laminate:
      price: 0.6
      unit: m^2
    gold:
      big:
        price: 1.8
        unit: m^2
      small:
        price: 1.5
        unit: m^2
      extra:
        price: 0.15
        unit: piece
    uv:
      big:
        price: 1.5
        unit: m^2
      small:
        price: 0.2
        unit: piece
      threshold: 300
  scale: 1.0
book:
  bigSize:
    width: 889
    length: 1194
    unit: mm
  smallSize:
    width: 787
    length: 1080
    unit: mm
  priceList:
    price:
      big:
        copper:
          80g: 0.7
          105g: 0.85
          128g: 1
          157g: 1.2
          200g: 1.55
          250g: 1.9
          300g: 2.3
      small:
        copper:
          80g: 0.6
          105g: 0.75
          128g: 0.85
          157g: 0.98
          200g: 1.3
          250g: 1.65
          300g: 2
    unit: piece
  process:
    print:
      price: 0.4
      unit: piece
    laminate:
      price: 0.8
      unit: m^2
  bind:
    fold:
      list:
        1f: 0.008
        2f: 0.016
        3f: 0.018
        4f: 0.024
        5f: 0.030
      unit: page
      threshold: 50
    staple:
      list:
        8k: 0.015
        16k: 0.01
      unit: page
      threshold: 80
    glue:
      list:
        24p-30p: 0.30
        32p-40p: 0.40
        42p-62p: 0.50
        64p-80p: 0.60
        108p: 1.20
        200p-228p: 1.40
        304p-320p: 1.80
      unit: book
      threshold: 200
label:
  price:
    general: 3.5
    removable: 3.8
    pvc: 6
  unit: m^2
  scale: 1.0
