box:
  size:
  - big
  - small
  material:
  - grey
  - white
  weight:
  - 250g
  - 300g
  - 350g
  - 400g
  gold:
  - big
  - small
  uv:
  - big
  - small
book:
  k:
  - 1k
  - 2k
  - 3k
  - 4k
  - 5k
  - 6k
  - 7k
  - 8k
  - 9k
  - 10k
  - 11k
  - 12k
  - 13k
  - 14k
  - 15k
  - 16k
  - 18k
  - 20k
  - 21k
  - 24k
  - 25k
  - 26k
  - 27k
  - 28k
  - 30k
  - 32k
  - 36k
  - 40k
  - 50k
  - 64k
  size:
  - big
  - small
  material:
  - copper
  bind:
  - fold
  - staple
  - glue
  bindKey:
    fold:
    - 1f
    - 2f
    - 3f
    - 4f
    - 5f
    staple:
    - 8k
    - 16k
    glue:
    - 24p-30p
    - 32p-40p
    - 42p-62p
    - 64p-80p
    - 108p
    - 200p-228p
    - 304p-320p
  weight:
  - 80g
  - 105g
  - 128g
  - 157g
  - 200g
  - 250g
  - 300g
label:
  type:
  - general
  - removable
  - pvc